### ISSUE TITLE
Slides to be presented in the workshop

### ISSUE THREAD

**Issue by xavigiro** [mcv-m6-video/class2016#11]
Please use this issue to submit your slides for today's workshop. Sorry for the delay in creating the issue.

**Comment by mandorra** [comment]
Team 3: https://docs.google.com/presentation/d/1zIW3dGdqCNH6dXD56JELMRdYK8DHaZEr2EbAoB_RgPA/pub?start=true&loop=true&delayms=3000

**Comment by Akhil-Gurram** [comment]
Team 5:  https://docs.google.com/presentation/d/1GQTmfILK6Sfm_n9z0EGqcxunDDZXaUvXEwikl20aCTY/edit

**Comment by adriaciurana** [comment]
Team 4:https://docs.google.com/presentation/d/16IXCxF2YpysdliPm6mvZCtJd-bUgXfPlMwwg7lVU4Rs/edit?usp=sharing

**Comment by mnc537** [comment]
Team 2: https://docs.google.com/presentation/d/1EZgeanAvO5I3AYQtif86XSD8vJIjDxYPCl8CBPZnfOc/edit?usp=sharing

**Comment by uldir9** [comment]
Team 7:

https://docs.google.com/presentation/d/1css5xBV2xr68VLIYaWTwE4lujHBXx7s38qSu_Rw3iuU/edit?usp=sharing

**Comment by gombru** [comment]
Team 6:
https://docs.google.com/presentation/d/1ve3dIE_WuKVpBBcvivX5wfqY6P7U7PjyYpO9pDpof04/edit?usp=sharing

**Comment by alc1218** [comment]
Team 1:

https://docs.google.com/presentation/d/1Xc3X30owMFZMpPqjlkSgeidAEFXaNebdTGe4v6QeiBQ/edit?ts=56b0a3b2#slide=id.p
