### ISSUE TITLE
Submit your final report here.

### ISSUE THREAD

**Issue by xavigiro** [mcv-m6-video/class2016#9]
Submit your final report here.

**Comment by AgFlores** [comment]
Group 7, paper:
https://github.com/mcv-m4-video/Team7/blob/master/week5/Group7Paper.pdf

Web:
http://mcv-m4-video.github.io/Team7/

**Comment by mandorra** [comment]
Team3: http://mcv-m4-video.github.io/Team3/

(Paper and code available at the website)

**Comment by priba** [comment]
Team 4: http://mcv-m4-video.github.io/Team4/

(All the files are linked in the webpage)

**Comment by a-velasco** [comment]
Team 6: http://mcv-m4-video.github.io/team6
(All files linked in webpage)

**Comment by scanyameres** [comment]
Team 1: http://mcv-m4-video.github.io/Team_1/
All files are already linked in the webpage.

**Comment by Akhil-Gurram** [comment]
Team 5: http://mcv-m4-video.github.io/Team-5.
(All files linked in webpage).

**Comment by acalafell** [comment]
Tema 2: http://mcv-m4-video.github.io/Team2/
